---
title: "06 Project organization"
author: 
  - "STAT 550"
  - "Daniel J. McDonald"
date: 'Last modified - `r Sys.Date()`'
---
class: middle, inverse, center



### I urge you to consult:

[.h2[ Karl Broman's Notes]](https://kbroman.org/Tools4RR/assets/lectures/06_org_eda_withnotes.pdf)

---
class: middle, inverse, center

# Before I forget, .primary[BACK UP YOUR STUFF!!]

---

## Organizing your stuff

.pull-left[
```
├── Advising
│   ├── arash
│   ├── gian-carlo
├── CV
├── Computing
│   ├── FKF
│   ├── batchtools.slurm.tmpl
│   ├── computecanada_notes.md
│   ├── ghclass
│   └── spatio-temporal-exp-fam
├── Grants
│   ├── B&E JSM 2010
│   ├── CANSSI RRP 2020
│   ├── NSERC 2020
├── LettersofRec
├── Manuscripts
│   ├── Old
├── Referee reports
├── Talks
│   ├── JobTalk2020
│   ├── ubc-stat-covid-talk
│   └── utoronto-grad-advice
├── Teaching
│   ├── stat-406
│   ├── stat-550
│   ├── zzzz CMU TA
│   └── zzzz booth
└── Website
```
]

.pull-right[
### Inside a project

```
.
├── README.md
├── Summary of Goals.rtf
├── cluster_output
├── code
├── data
├── dsges-github.Rproj
├── manuscript
└── waldman-triage
```

* Separate raw / processed data
* Include a README
* Ideally have a MAKEFILE
* Under version control, shared with collaborator



]



---

## Basic principles

* Develop your own system

* Put everything in a common directory

* Be consistent
    – directory structure; names

* Separate raw from processed data
* Separate code from data

* It should be obvious what code created what files, and what the dependencies are.

* .secondary[No hand-editing of data files]

* .secondary[Don’t use spaces in file names]

* Use relative paths, not absolute paths
  - `../blah` not `~/blah` or `/users/dajmcdon/blah`
  - The `{here}` package in `R` is great for this

---

## Problem: Coordinating with collaborators

* Where to put data that multiple people will work with?

* Where to put intermediate/processed data?

* Where to indicate the code that created those processed data files?

* How to divvy up tasks and know who did what?

* Need to agree on directory structure and file naming conventions

.center[.secondary[Github is (I think) the ideal solution, but not always feasible.]]

--

### Problem: Collaborators who don’t use Github
* Use Github yourself
* Copy files to/from some shared space
    - Ideally, in an automated way (Dropbox, S3 Bucket)
    - I avoid Word at all costs. Google Docs if needed.
    - Word and Git do not mix
    - .secondary[Last resort:] Word file in Dropbox. Everything else nicely organized on your end. Rmd file with similar structure to Manuscript that does the analysis.
* Commit their changes.

---

## Using Rmarkdown for most things

### Your goal is to .secondary[Avoid at all costs]:

* "How did I create this plot?"

* "Why did I decide to omit those six samples?"

* "Where (on the web) did I find these data?"

* "What was that interesting gene/feature/predictor?"

---
class: middle, center, inverse

# My workflow


---

## The basics

1. I do all class documents in Rmarkdown. Notes, slides, etc. Organized in Github repos:
```
├── github-org
│  ├── admm-cd
│  ├── class-management
│  ├── convexity-exercises
...
│  └── useful-materials
├── instructor-private
│  ├── README.md
│  └── brief-summary
└── student-public
    ├── README.md
    ├── docs
    └── lecture-slides
```

2. When working out new code for a project, I use a combination of R package (as I get close to completion) and Rmarkdown.
    - Many stat journals require reproducible, documented code. An R package is great for this.
    - Rmarkdown alone lets me document as I go.
    
3. My students are required to give me reports in Rmarkdown (for practice).

---

## For professional presentations

~~I use Rmarkdown + Beamer:~~ Now I use Rmd + Xaringan (see [`dajmcdon/talk-template`](https://github.com/dajmcdon/talk-template))

```
---
title: "Trend filtering in exponential families"
author: |
  | Daniel J. McDonald
  | University of British Columbia
  | \alert{\footnotesize \url{dajmcdon.github.io}}
date: |  
  | 4 March 2020
output: 
  beamer_presentation:
    latex_engine: pdflatex
    includes:
      in_header: macros.tex
classoption: "aspectratio=169"
---
```

The `includes` statement loads all the LaTeX macros I need, specifies Beamer choices.

---


## The old presentation

1. Write lots of LaTeX, R code in separate files
2. Need a figure. Run R code, get figure, save as pdf.
3. Recompile LaTeX. Axes are unreadable. Back to R, rerun R code,...
4. Recompile LaTeX. Can't distinguish lines. Back to R, rerun R code,...
5. Etc, etc.

Now:  
Code and LaTeX live in one file. I just recompile.

---


## The old manuscript

Similar to the old presentation.

Now:  
1. R package with documented code, available on Github.  
2. One script to run the analysis, one to gather the results.  
3. One Rmd file to take in the results, do preprocessing, generate all figures.  
4. LaTeX file on Journal style.

## The optimal

Same as above but with a Makefile to automatically run 1-4.
